
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  portainer:
    title: "Portainer"
    url: "http://odroid.local:9000/#/containers"
    icon: mdi:docker
    require_admin: true
  zigbee2mqtt:
    title: "zigbee2mqtt"
    url: "http://odroid.local:8080"
    icon: mdi:zigbee
    require_admin: true
  plex:
    title: "Plex"
    url: "http://odroid.local:32400/web"
    icon: mdi:plex
  duplicati:
    title: "Duplicati"
    url: "http://odroid.local:8200"
    icon: mdi:backup-restore
    require_admin: true
